
title: My Resume
url: 'http://minhduc27.github.io'
baseurl: "" #change it according to your repository name



# Profile information
yourname: Ho Tran Minh Duc  ## put your name
title: 'Embedded Software &amp; System Engineer'  ## your title
location: Thu Duc District , HCM City


## Social Profiles
facebook: https://www.facebook.com/minhduc.kido/  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/%C4%91%E1%BB%A9c-h%E1%BB%93-b64673230  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
