
title: My Resume
url: 'http://tuanhtran99.github.io'
baseurl: "" #change it according to your repository name



# Profile information
yourname: Tran Tu Anh  ## put your name
title: 'Embedded Software &amp; System Engineer'  ## your title
location: Thu Duc District , HCM City


## Social Profiles
facebook: https://www.facebook.com/minhduc.kido/  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
#linkedin: http://www.linkedin.com  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
